### ISSUE TITLE
Update Guzzle

### ISSUE THREAD

**Issue by rolfvandekrol** [hoppinger/wp-relinquish#23]
WP Relinquish currently uses Guzzle 5.2.x. This version is vulnerable to the [HTTPoxy attack](https://httpoxy.org/). In order to be safe, WP Relinquish should upgrade to 6.2.1.

**Comment by sebastiaandegeus** [comment]
The issue is fixed in 5.3.1
https://github.com/guzzle/guzzle/commit/70f1fa53b71c4647bf2762c09068a95f77e12fb8

We will use `5.3.1` for the fix so we don't have to upgrade the major version.

Thank you @rolfvandekrol

**Comment by sebastiaandegeus** [comment]
Fixed in: https://github.com/wponrails/wp-relinquish/releases/tag/v0.3.0
